/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_saorsa_javaandlinux_jni_CreateNamedPipeJNI */

#ifndef _Included_com_saorsa_javaandlinux_jni_CreateNamedPipeJNI
#define _Included_com_saorsa_javaandlinux_jni_CreateNamedPipeJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_saorsa_javaandlinux_jni_CreateNamedPipeJNI
 * Method:    create
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_saorsa_javaandlinux_jni_CreateNamedPipeJNI_create
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
